package mjg

import groovy.sql.Sql

@GrabConfig(systemClassLoader=true)
@Grab(group='com.h2database', module='h2', version='1.2.140')
Sql sql = Sql.newInstance(url:'jdbc:h2:mem:',driver:'org.h2.Driver')

sql.execute '''
    create table coordinates (
        id bigint generated by default as identity,
        angle double not null,
        x double not null,
        y double not null,
        primary key (id)
    )
'''

sql.execute """
    insert into coordinates values
    (null, 0, 1, 0), (null, ${Math.PI/2}, 0, 1), 
    (null, $Math.PI, -1, 0), (null, ${-3*Math.PI/2}, 0, -1) 
"""

assert sql.rows('select * from coordinates').size() == 4

sql.eachRow('select * from coordinates') { row ->
    println "$row.id, $row.angle, $row.x, $row.y"
}
